import type { AiSystem, DataContract, DriftEvent, AuditEvent } from "./types";

export const MOCK_SYSTEMS: AiSystem[] = [
  {
    id: "mock-sys-001",
    name: "Claims Triage AI",
    owner: "Insurance Ops",
    purpose: "Prioritise and route insurance claims",
    riskClass: "high",
    riskBasis: "Eligibility and access to essential private services",
    deploymentRegion: "EU",
    evidenceCoverage: 72,
    evalScore: 78,
    dataContractStatus: "BREACH",
    releaseDecision: "blocked",
    openGaps: ["Human oversight SOP missing", "Bias eval below threshold"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mock-sys-002",
    name: "HR Candidate Screener",
    owner: "People Systems",
    purpose: "Rank and shortlist job applicants",
    riskClass: "high",
    riskBasis: "Employment access and ranking",
    deploymentRegion: "EU",
    evidenceCoverage: 84,
    evalScore: 82,
    dataContractStatus: "WARNING",
    releaseDecision: "review",
    openGaps: ["Data lineage stale", "Reviewer calibration required"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mock-sys-003",
    name: "Bank KYC Assistant",
    owner: "Financial Crime",
    purpose: "Credit, onboarding, and fraud control support",
    riskClass: "high",
    riskBasis: "Credit, onboarding, and fraud control support",
    deploymentRegion: "EU",
    evidenceCoverage: 91,
    evalScore: 88,
    dataContractStatus: "HEALTHY",
    releaseDecision: "pass",
    openGaps: ["Quarterly red-team due in 9 days"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mock-sys-004",
    name: "Support RAG Copilot",
    owner: "Customer Success",
    purpose: "Customer-facing assistant with transparency duty",
    riskClass: "limited",
    riskBasis: "Customer-facing assistant with transparency duty",
    deploymentRegion: "EU",
    evidenceCoverage: 88,
    evalScore: 86,
    dataContractStatus: "HEALTHY",
    releaseDecision: "pass",
    openGaps: ["Update chatbot disclosure copy"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mock-sys-005",
    name: "Clinical Intake Summarizer",
    owner: "Health Product",
    purpose: "Healthcare workflow support with PHI controls",
    riskClass: "high",
    riskBasis: "Healthcare workflow support with PHI controls",
    deploymentRegion: "EU",
    evidenceCoverage: 81,
    evalScore: 73,
    dataContractStatus: "BREACH",
    releaseDecision: "blocked",
    openGaps: ["PHI masking failed", "Audit justification missing"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_CONTRACTS: DataContract[] = [
  {
    id: "mock-contract-001",
    systemId: "mock-sys-001",
    name: "claims_events.v4",
    owner: "Insurance Data",
    version: "v4",
    status: "BREACH",
    coverage: 68,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mock-contract-002",
    systemId: "mock-sys-002",
    name: "candidate_profiles.v2",
    owner: "People Analytics",
    version: "v2",
    status: "WARNING",
    coverage: 81,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mock-contract-003",
    systemId: "mock-sys-003",
    name: "kyc_decisions.v7",
    owner: "Financial Crime",
    version: "v7",
    status: "HEALTHY",
    coverage: 94,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mock-contract-004",
    systemId: "mock-sys-005",
    name: "clinical_notes.v3",
    owner: "Health Product",
    version: "v3",
    status: "BREACH",
    coverage: 63,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_DRIFT_EVENTS: DriftEvent[] = [
  {
    id: "mock-drift-001",
    contractId: "mock-contract-001",
    severity: "BREACH",
    field: "denial_reason_category",
    description: "New field denial_reason_category is not mapped to fairness monitoring.",
    status: "OPEN",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mock-drift-002",
    contractId: "mock-contract-002",
    severity: "WARNING",
    field: "education_history",
    description: "Education history optionality changed from required to nullable.",
    status: "OPEN",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "mock-drift-003",
    contractId: "mock-contract-004",
    severity: "BREACH",
    field: "patient_language",
    description: "PHI redaction contract missing for locale-specific identifiers.",
    status: "OPEN",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "mock-audit-001",
    systemId: "mock-sys-001",
    actorId: null,
    eventType: "release_gate.calculated",
    resourceType: "ai_system",
    resourceId: "mock-sys-001",
    payload: { decision: "BLOCKED", reason: "faithfulness below threshold" },
    createdAt: new Date(Date.now() - 300_000).toISOString(),
  },
  {
    id: "mock-audit-002",
    systemId: "mock-sys-001",
    actorId: null,
    eventType: "evidence.query_answered",
    resourceType: "evidence_query",
    resourceId: null,
    payload: { question: "Which controls block the Claims Triage AI?" },
    createdAt: new Date(Date.now() - 600_000).toISOString(),
  },
  {
    id: "mock-audit-003",
    systemId: "mock-sys-005",
    actorId: null,
    eventType: "data_contract.drift_detected",
    resourceType: "data_contract",
    resourceId: "mock-contract-004",
    payload: { severity: "BREACH", field: "patient_language" },
    createdAt: new Date(Date.now() - 1_440_000).toISOString(),
  },
];
