import type {
  AiSystem,
  DataContract,
  DriftEvent,
  AuditEvent,
  ApprovalWorkflow,
  WorkflowNotification,
} from "./types";

const d = (daysAgo: number, hoursAgo = 0) =>
  new Date(Date.now() - daysAgo * 86_400_000 - hoursAgo * 3_600_000).toISOString();

export const MOCK_SYSTEMS: AiSystem[] = [
  {
    id: "mock-sys-001",
    name: "Claims Triage AI",
    owner: "Insurance Ops",
    purpose: "Prioritise and route insurance claims for manual review and settlement",
    riskClass: "high",
    riskBasis: "Art. 6(2) Annex III §5(b) — automated decisions on eligibility for essential private services",
    deploymentRegion: "EU",
    evidenceCoverage: 72,
    evalScore: 78,
    dataContractStatus: "BREACH",
    releaseDecision: "blocked",
    openGaps: [
      "Human oversight SOP not indexed — Art. 14 requires reviewer override procedure",
      "Bias eval score 78% below 85% gate threshold on denial_reason_category slice",
      "DPIA sign-off missing for v4 claims schema change",
    ],
    createdAt: d(62),
    updatedAt: d(1, 3),
  },
  {
    id: "mock-sys-002",
    name: "HR Candidate Screener",
    owner: "People Systems",
    purpose: "Rank and shortlist job applicants from ATS pipeline using structured scoring",
    riskClass: "high",
    riskBasis: "Art. 6(2) Annex III §4 — recruitment, selection, and promotion decisions",
    deploymentRegion: "EU",
    evidenceCoverage: 84,
    evalScore: 82,
    dataContractStatus: "WARNING",
    releaseDecision: "review",
    openGaps: [
      "education_history field now nullable — fairness slice rerun required before release",
      "Reviewer calibration session not documented for Q2 2026",
    ],
    createdAt: d(48),
    updatedAt: d(0, 6),
  },
  {
    id: "mock-sys-003",
    name: "Bank KYC Assistant",
    owner: "Financial Crime",
    purpose: "Support onboarding analysts with KYC document checks and fraud signal scoring",
    riskClass: "high",
    riskBasis: "Art. 6(2) Annex III §5(b) — creditworthiness, fraud, and anti-money-laundering controls",
    deploymentRegion: "EU",
    evidenceCoverage: 91,
    evalScore: 88,
    dataContractStatus: "HEALTHY",
    releaseDecision: "pass",
    openGaps: [
      "Quarterly red-team exercise due in 9 days — schedule before next release window",
    ],
    createdAt: d(120),
    updatedAt: d(3),
  },
  {
    id: "mock-sys-004",
    name: "Support RAG Copilot",
    owner: "Customer Success",
    purpose: "Answer customer queries grounded on product docs with source citations",
    riskClass: "limited",
    riskBasis: "Art. 52 — transparency obligation for AI interacting with natural persons",
    deploymentRegion: "EU",
    evidenceCoverage: 88,
    evalScore: 86,
    dataContractStatus: "HEALTHY",
    releaseDecision: "pass",
    openGaps: [
      "Chatbot disclosure banner copy not yet updated to Art. 52(1) wording",
    ],
    createdAt: d(35),
    updatedAt: d(5),
  },
  {
    id: "mock-sys-005",
    name: "Clinical Intake Summarizer",
    owner: "Health Product",
    purpose: "Generate structured intake summaries from unstructured clinical notes for triage staff",
    riskClass: "high",
    riskBasis: "Art. 6(2) Annex III §5(a) — decisions in health and social care services",
    deploymentRegion: "EU",
    evidenceCoverage: 81,
    evalScore: 73,
    dataContractStatus: "BREACH",
    releaseDecision: "blocked",
    openGaps: [
      "PHI redaction contract missing for locale-specific identifiers (patient_language field)",
      "Audit justification log required before release — Art. 12(1) logging obligation",
      "Faithfulness eval 73% below 85% gate — hallucination rate unacceptable in clinical context",
    ],
    createdAt: d(27),
    updatedAt: d(0, 2),
  },
];

export const MOCK_CONTRACTS: DataContract[] = [
  {
    id: "mock-contract-001",
    systemId: "mock-sys-001",
    name: "claims_events.v4",
    owner: "Insurance Data",
    version: "v4",
    status: "BREACH",
    coverage: 68,
    createdAt: d(62),
    updatedAt: d(1, 3),
  },
  {
    id: "mock-contract-002",
    systemId: "mock-sys-002",
    name: "candidate_profiles.v2",
    owner: "People Analytics",
    version: "v2",
    status: "WARNING",
    coverage: 81,
    createdAt: d(48),
    updatedAt: d(0, 6),
  },
  {
    id: "mock-contract-003",
    systemId: "mock-sys-003",
    name: "kyc_decisions.v7",
    owner: "Financial Crime",
    version: "v7",
    status: "HEALTHY",
    coverage: 94,
    createdAt: d(120),
    updatedAt: d(3),
  },
  {
    id: "mock-contract-004",
    systemId: "mock-sys-004",
    name: "support_kb_chunks.v3",
    owner: "Knowledge Ops",
    version: "v3",
    status: "HEALTHY",
    coverage: 91,
    createdAt: d(35),
    updatedAt: d(5),
  },
  {
    id: "mock-contract-005",
    systemId: "mock-sys-005",
    name: "clinical_notes.v3",
    owner: "Health Product",
    version: "v3",
    status: "BREACH",
    coverage: 63,
    createdAt: d(27),
    updatedAt: d(0, 2),
  },
];

export const MOCK_DRIFT_EVENTS: DriftEvent[] = [
  {
    id: "mock-drift-001",
    contractId: "mock-contract-001",
    severity: "BREACH",
    field: "denial_reason_category",
    description:
      "New enum value 'FRAUD_SUSPECTED' added without fairness monitoring mapping. Affects protected-group slice analysis.",
    status: "OPEN",
    createdAt: d(1, 3),
    updatedAt: d(1, 3),
  },
  {
    id: "mock-drift-002",
    contractId: "mock-contract-001",
    severity: "WARNING",
    field: "claim_amount_band",
    description:
      "Bucketing changed from 5 bands to 3 — existing eval dataset uses old band labels, rerun needed.",
    status: "OPEN",
    createdAt: d(4),
    updatedAt: d(4),
  },
  {
    id: "mock-drift-003",
    contractId: "mock-contract-002",
    severity: "WARNING",
    field: "education_history",
    description:
      "Field optionality changed from required to nullable. Fairness slice on education_history no longer guaranteed to run.",
    status: "OPEN",
    createdAt: d(0, 6),
    updatedAt: d(0, 6),
  },
  {
    id: "mock-drift-004",
    contractId: "mock-contract-005",
    severity: "BREACH",
    field: "patient_language",
    description:
      "PHI redaction contract does not cover locale-specific name patterns in patient_language field. GDPR Art. 9 exposure.",
    status: "OPEN",
    createdAt: d(0, 2),
    updatedAt: d(0, 2),
  },
  {
    id: "mock-drift-005",
    contractId: "mock-contract-005",
    severity: "BREACH",
    field: "diagnosis_code_icd11",
    description:
      "ICD-11 code column added without schema migration — downstream PHI masking pipeline silently skipping new codes.",
    status: "OPEN",
    createdAt: d(2),
    updatedAt: d(2),
  },
];

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "mock-audit-001",
    systemId: "mock-sys-001",
    actorId: "actor-priya",
    eventType: "RELEASE_GATE_CALCULATED",
    resourceType: "ai_system",
    resourceId: "mock-sys-001",
    payload: { decision: "BLOCKED", reason: "bias eval 78% < 85% gate; human oversight SOP missing" },
    createdAt: d(0, 0.5),
  },
  {
    id: "mock-audit-002",
    systemId: "mock-sys-005",
    actorId: null,
    eventType: "DRIFT_EVENT_CREATED",
    resourceType: "data_contract",
    resourceId: "mock-contract-005",
    payload: { severity: "BREACH", field: "diagnosis_code_icd11", contractName: "clinical_notes.v3" },
    createdAt: d(0, 2),
  },
  {
    id: "mock-audit-003",
    systemId: "mock-sys-002",
    actorId: "actor-marco",
    eventType: "EVIDENCE_INDEXED",
    resourceType: "evidence_document",
    resourceId: "doc-hr-dpia-v3",
    payload: { title: "HR Screener DPIA v3", type: "DPIA", chunks: 14 },
    createdAt: d(0, 5),
  },
  {
    id: "mock-audit-004",
    systemId: "mock-sys-001",
    actorId: "actor-priya",
    eventType: "EVIDENCE_QUERIED",
    resourceType: "evidence_query",
    resourceId: null,
    payload: { question: "Which controls block the Claims Triage AI release?", confidence: 0.82 },
    createdAt: d(0, 6),
  },
  {
    id: "mock-audit-005",
    systemId: "mock-sys-003",
    actorId: "actor-leo",
    eventType: "RELEASE_GATE_CALCULATED",
    resourceType: "ai_system",
    resourceId: "mock-sys-003",
    payload: { decision: "PASS", evalScore: 88, evidenceCoverage: 91, contractStatus: "HEALTHY" },
    createdAt: d(3),
  },
  {
    id: "mock-audit-006",
    systemId: "mock-sys-001",
    actorId: null,
    eventType: "DRIFT_EVENT_CREATED",
    resourceType: "data_contract",
    resourceId: "mock-contract-001",
    payload: { severity: "BREACH", field: "denial_reason_category", contractName: "claims_events.v4" },
    createdAt: d(1, 3),
  },
  {
    id: "mock-audit-007",
    systemId: "mock-sys-004",
    actorId: "actor-sofia",
    eventType: "EVIDENCE_INDEXED",
    resourceType: "evidence_document",
    resourceId: "doc-rag-disclosure",
    payload: { title: "Support Copilot Art. 52 Disclosure Policy", type: "POLICY", chunks: 6 },
    createdAt: d(5),
  },
  {
    id: "mock-audit-008",
    systemId: "mock-sys-002",
    actorId: null,
    eventType: "DRIFT_EVENT_CREATED",
    resourceType: "data_contract",
    resourceId: "mock-contract-002",
    payload: { severity: "WARNING", field: "education_history", contractName: "candidate_profiles.v2" },
    createdAt: d(0, 6),
  },
  {
    id: "mock-audit-009",
    systemId: "mock-sys-003",
    actorId: "actor-leo",
    eventType: "EVIDENCE_INDEXED",
    resourceType: "evidence_document",
    resourceId: "doc-kyc-model-card",
    payload: { title: "KYC Assistant Model Card v7", type: "MODEL_CARD", chunks: 22 },
    createdAt: d(7),
  },
  {
    id: "mock-audit-010",
    systemId: "mock-sys-005",
    actorId: "actor-priya",
    eventType: "RELEASE_GATE_CALCULATED",
    resourceType: "ai_system",
    resourceId: "mock-sys-005",
    payload: { decision: "BLOCKED", reason: "faithfulness 73% < 85%; PHI breach on clinical_notes.v3" },
    createdAt: d(0, 2.5),
  },
];

export const MOCK_WORKFLOWS: Record<string, ApprovalWorkflow[]> = {
  "mock-sys-001": [
    {
      id: "mock-wf-001",
      systemId: "mock-sys-001",
      trigger: "SYSTEM_CREATED",
      status: "OPEN",
      openedAt: d(1, 3),
      closedAt: null,
      createdAt: d(1, 3),
      stages: [
        {
          id: "mock-stage-001",
          workflowId: "mock-wf-001",
          stageOrder: 1,
          stageType: "ENG_LEAD_REVIEW",
          requiredRole: "AI_ENGINEERING_LEAD",
          assignedReviewerId: "00000000-0000-0000-0000-000000000102",
          status: "PENDING",
          actorId: null,
          rationale: null,
          oversightEvidence: null,
          actedAt: null,
          notificationSentAt: d(1, 3),
          createdAt: d(1, 3),
        },
        {
          id: "mock-stage-002",
          workflowId: "mock-wf-001",
          stageOrder: 2,
          stageType: "COMPLIANCE_REVIEW",
          requiredRole: "COMPLIANCE_OFFICER",
          assignedReviewerId: "00000000-0000-0000-0000-000000000101",
          status: "PENDING",
          actorId: null,
          rationale: null,
          oversightEvidence: null,
          actedAt: null,
          notificationSentAt: null,
          createdAt: d(1, 3),
        },
        {
          id: "mock-stage-003",
          workflowId: "mock-wf-001",
          stageOrder: 3,
          stageType: "LEGAL_SIGNOFF",
          requiredRole: "LEGAL_COUNSEL",
          assignedReviewerId: "00000000-0000-0000-0000-000000000104",
          status: "PENDING",
          actorId: null,
          rationale: null,
          oversightEvidence: null,
          actedAt: null,
          notificationSentAt: null,
          createdAt: d(1, 3),
        },
      ],
    },
  ],
  "mock-sys-004": [
    {
      id: "mock-wf-004",
      systemId: "mock-sys-004",
      trigger: "SYSTEM_CREATED",
      status: "APPROVED",
      openedAt: d(30),
      closedAt: d(28),
      createdAt: d(30),
      stages: [
        {
          id: "mock-stage-010",
          workflowId: "mock-wf-004",
          stageOrder: 1,
          stageType: "ENG_LEAD_REVIEW",
          requiredRole: "AI_ENGINEERING_LEAD",
          assignedReviewerId: "00000000-0000-0000-0000-000000000102",
          status: "APPROVED",
          actorId: "00000000-0000-0000-0000-000000000102",
          rationale: "Eval metrics all green. Faithfulness 0.91, bias pass rate 0.94.",
          oversightEvidence: null,
          actedAt: d(29),
          notificationSentAt: d(30),
          createdAt: d(30),
        },
        {
          id: "mock-stage-011",
          workflowId: "mock-wf-004",
          stageOrder: 2,
          stageType: "COMPLIANCE_REVIEW",
          requiredRole: "COMPLIANCE_OFFICER",
          assignedReviewerId: "00000000-0000-0000-0000-000000000101",
          status: "APPROVED",
          actorId: "00000000-0000-0000-0000-000000000101",
          rationale: "Evidence coverage 88%. Art. 52 transparency obligation noted in open gaps — acceptable for LIMITED risk.",
          oversightEvidence: null,
          actedAt: d(28),
          notificationSentAt: d(29),
          createdAt: d(30),
        },
        {
          id: "mock-stage-012",
          workflowId: "mock-wf-004",
          stageOrder: 3,
          stageType: "LEGAL_SIGNOFF",
          requiredRole: "LEGAL_COUNSEL",
          assignedReviewerId: "00000000-0000-0000-0000-000000000104",
          status: "SKIPPED",
          actorId: null,
          rationale: null,
          oversightEvidence: null,
          actedAt: null,
          notificationSentAt: null,
          createdAt: d(30),
        },
      ],
    },
  ],
};

/** Flattened open workflows for offline approvals queue demos. */
export const MOCK_OPEN_WORKFLOWS: ApprovalWorkflow[] = Object.values(MOCK_WORKFLOWS)
  .flat()
  .filter((workflow) => workflow.status === "OPEN");

/** Demo "mine" queue — open workflows with a pending stage. */
export const MOCK_MY_WORKFLOWS: ApprovalWorkflow[] = MOCK_OPEN_WORKFLOWS;

export const MOCK_NOTIFICATIONS: WorkflowNotification[] = [
  {
    id: "mock-notif-001",
    workflowId: "mock-wf-001",
    stageId: "mock-stage-001",
    recipientId: "00000000-0000-0000-0000-000000000102",
    eventType: "WORKFLOW_STAGE_ASSIGNED",
    message: "Approval required for ENG LEAD REVIEW",
    readAt: null,
    createdAt: d(1, 3),
  },
];
