#!/usr/bin/env bash
# Mac-side: run ONLY the Next.js dashboard, pointed at the Dell Docker backend.
# Backend is never started on this machine — use Docker on Dell only.
#
# Usage (from repo root):
#   ./scripts/dev-frontend-dell.sh
#   ./scripts/dev-frontend-dell.sh --skip-health   # start UI even if API is down
#
# Requires: Dell stack healthy at http://192.168.50.88:9080 (see scripts/backend-dell.ps1)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Prefer local lab secrets (gitignored)
if [[ -f "$ROOT/.local/dell-ssh.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.local/dell-ssh.env"
  set +a
fi

DELL_HOST="${DELL_HOST:-192.168.50.88}"
API_PORT="${API_HOST_PORT:-9080}"
API_BASE="${ASSURANCE_API_BASE_URL:-http://${DELL_HOST}:${API_PORT}}"
SITE_URL="${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}"
SKIP_HEALTH=0
[[ "${1:-}" == "--skip-health" ]] && SKIP_HEALTH=1

health_url="${API_BASE%/}/actuator/health"

echo "==> Frontend (Mac) → backend (Dell Docker)"
echo "    ASSURANCE_API_BASE_URL=$API_BASE"
echo "    NEXT_PUBLIC_SITE_URL=$SITE_URL"
echo ""

if [[ "$SKIP_HEALTH" -eq 0 ]]; then
  echo "==> Checking Dell API: $health_url"
  if ! curl -fsS --connect-timeout 3 "$health_url" >/dev/null 2>&1; then
    cat <<EOF >&2
error: Dell API is not healthy at $health_url

On the Dell (PowerShell), start Docker stack only:
  cd D:\\Projects\\eu-ai-assurance-os
  .\\scripts\\backend-dell.ps1

Or from Mac when SSH works:
  ./scripts/deploy-dell.sh

Then re-run: ./scripts/dev-frontend-dell.sh
EOF
    exit 1
  fi
  echo "    health OK"
  echo ""
fi

# Wire dashboard BFF → Dell (browser always hits /api/proxy on :3000)
mkdir -p apps/dashboard
cat > apps/dashboard/.env.local <<EOF
# Generated by scripts/dev-frontend-dell.sh — DO NOT COMMIT
# Browser → Next.js BFF (localhost:3000) → Spring API on Dell Docker
ASSURANCE_API_BASE_URL=$API_BASE
NEXT_PUBLIC_SITE_URL=$SITE_URL
EOF

echo "==> Wrote apps/dashboard/.env.local"
echo "==> Starting dashboard on http://localhost:3000"
echo "    Login (bootstrap): compliance@example.com / dev-local-password-only"
echo ""

cd apps/dashboard
if [[ ! -d node_modules ]]; then
  echo "==> npm install (first run)"
  npm install
fi
exec npm run dev -- --port 3000
